# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "* * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - run: echo "$(date +'%Y-%m-%dT%H:%M:%S')" > ./file-${{ github.event.repository.updated_at}}.txt

                  
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          # Commit message
          commit_message: "auto commit from github actions"# optional, default is Apply automatic changes
          # Git branch name, where changes should be pushed too. Required if Action is used on the `pull_request` event
          branch: branch_${{ github.event.repository.updated_at}}# optional, default is ${{ github.head_ref }}
          # Local file path to the git repository. Defaults to the current directory (`.`)
          repository: . # optional, default is .
      
            
