name: ansible-workflow
on: [pull_request]
run-name: ansible 
  
jobs:
  run_ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository on the runner
        uses: actions/checkout@v4 
      - name: ping
        working-directory: ansible/inventory
        run: ansible -i hosts all -m ping
